### ISSUE TITLE
How to setup echo bot

### ISSUE THREAD

**Issue by AliAyub007** [line/line-bot-sdk-nodejs#1]
Hello, Can you please kindly explain how can I make echo test bot run? I made index.js in which I wrote the code for echo and in config I have defined my secret and key. I deployed that to heroku but bot didn't work and messages were sent normally like chat to bot.

**Comment by noraesae** [comment]
Hi, I have some questions before providing an answer.

1. Did you install deps? The echo bot example uses `express` and sdk, both of which specified in `package.json` of the example.
2. Did you register dev center account and set callback URL? Please make sure that HTTPS is used.
3. Is your server accessible via the URL from external devices with HTTPS?

I also recommend you reading [Getting started with the Messaging API](https://developers.line.me/messaging-api/getting-started) if you have not yet.

If you have further questions, please feel free to ask me, with a bit more of details.

**Comment by AliAyub007** [comment]
Yes I have installed node js sdk and express. I have registered an account also and set webhook url. and I have done all this above and followed every step from getting started till last. 

1- Can it work in 1-1 chat? 
2- I am receiving automatic messages from bot but it's not echoing the messages sent.

**Comment by noraesae** [comment]
So your server is currently accessible via HTTPS, I guess? Then please check if a request is actually sent to the server via log. If it's not sent, you may not have finished webhook URL registration.

1. Yes, it works in 1-1 chats too.
1. Automatic messages have nothing to do with SDK. Please check if webhook URL is set correctly and a request is sent to your web server. If it's configured correctly on LINE developer console, a webhook request itself should be sent to your URL regardless of code.

**Comment by AliAyub007** [comment]
my app is giving me this error on heroku and it's not running.
![test](https://cloud.githubusercontent.com/assets/25840461/26023050/a9198b64-37cd-11e7-9459-3af0e48794d6.PNG)

For this reason I am getting application error. here is the webhook https://susi-linebot.herokuapp.com/

**Comment by AliAyub007** [comment]
'use strict';

const line = require('@line/bot-sdk');
const express = require('express');

// create LINE SDK client
const client = new line.Client(config);

// create Express app
// about Express itself: https://expressjs.com/
const app = express();

app.set('port', (process.env.PORT || 5000));
// register a webhook handler with middleware
// about the middleware, please refer to doc
app.post('/webhook', line.middleware(config), function(req, res) {
  Promise
    .all(req.body.events.map(handleEvent))
    .then(function(result){ res.json(result)});
});

// event handler
function handleEvent(event) {
  if (event.type !== 'message' || event.message.type !== 'text') {
    // ignore non-text-message event
    return Promise.resolve(null);
  }

  // create a echoing text message
  const echo = { type: 'text', text: event.message.text };

  // use reply API
  return client.replyMessage(event.replyToken, echo);
}

// listen on port
app.listen(app.get('port'), function() {
  console.log('Node app is running on port', app.get('port'));
});

**Config is defined with secret and access token**

**Comment by noraesae** [comment]
By the log, it seems like Heroku failed to start the app. According to the Heroku doc, you need to specify a `start` script in `package.json` It seems like none of SDK issues, so I close this for the time being.

For Heroku usage, please refer to its documentation.

- https://devcenter.heroku.com/articles/nodejs-support

Thanks for your report. Please ask me if there is an issue concerning the SDK.
