### ISSUE TITLE
How to solve the problem if we don't find sub menu "Bot Settings"?

### ISSUE THREAD

**Issue by mahadoang** [line/line-bot-sdk-nodejs#10]
I have some one issue with web LINE@ Manager.
When I try to add the existing line account but I don't see sub menu "Bot Settings"
Do you have the way to solve this issue? I notice that new account which has been created from web LINE@ Manager I can see this sub menu.

Created from web
![Create by Web](https://cloud.githubusercontent.com/assets/1937836/26664699/c58151a2-46bd-11e7-8b24-ba1d51ecc2cc.jpg)

Existing Account
![Existing Account](https://cloud.githubusercontent.com/assets/1937836/26664708/d2ffa7e8-46bd-11e7-8342-f9f8a36fb7e7.jpg)

Thank you in advance.

**Comment by noraesae** [comment]
This question is not relevant to this repository. If you have any problem or question of LINE services, please use the report form.

https://contact.line.me/serviceId/10829

Thanks
