### ISSUE TITLE
Member join/leave events

### ISSUE THREAD

**Issue by utatti** [line/line-bot-sdk-nodejs#105]
- Info: https://developers.line.biz/en/news/tags/messaging-api/
- API References
  + https://developers.line.biz/en/reference/messaging-api/#member-joined-event
  + https://developers.line.biz/en/reference/messaging-api/#member-left-event

**Comment by matijis1001** [comment]
why does my bot not detect member join events? while the message event  work?

this is the code :

app.post('/callback', line.middleware(config), (req, res) => {
  Promise
    .all(req.body.events.map(handleEvent))
    .then((result) => res.json(result))
    .catch((e)=>{
      console.log(e);
    });

});

function handleEvent(event) {
console.log(event);
}

the console log only detect message event like sticker,text,image but when someone leaving group this doesn't detect it

Please help, thanks...
