### ISSUE TITLE
member join event 

### ISSUE THREAD

**Issue by matijis1001** [line/line-bot-sdk-nodejs#114]
why does my bot not detect member join events? while the message event work?

this is the code :

app.post('/callback', line.middleware(config), (req, res) => {
Promise
.all(req.body.events.map(handleEvent))
.then((result) => res.json(result))
.catch((e)=>{
console.log(e);
});

});

function handleEvent(event) {
console.log(event);
}

the console log only detect message event like sticker,text,image but when someone leaving group this doesn't detect it

Please help, thanks...

**Comment by utatti** [comment]
Can you ensure if members have agreed to terms of bot usage in LINE? I guess `memberLeave` and `memberJoin` only work for users who agreed to the terms.

**Comment by matijis1001** [comment]
ah.. its work with member who adds the bot to the friends list or agreed to terms! but this is not effective, i want build bot that he can detect the member join and write them to database automaticly without the member agreed to the terms. Thank You!!

**Comment by micksatana** [comment]
@matijis1001 LINE don't allow you retrieve user info when the user does not agree to give the information. I believe this is correct behavior. If you agree so, kindly close the issue ;-)

**Comment by utatti** [comment]
There is a separate repository for feature requests or feedback, so please check it out.

- https://github.com/line/line-platform-feedback

I close this issue. Please feel free to let me know if there's further issues :)
