### ISSUE TITLE
Get number of messages sent

### ISSUE THREAD

**Issue by SombreroElGringo** [line/line-bot-sdk-nodejs#115]
-  Info: https://developers.line.biz/en/news/#new-endpoints-added-to-messaging-api-2019-01-17

- API :
 [Get number of sent reply](https://developers.line.biz/en/reference/messaging-api/#get-number-of-reply-messages)
[Get number of sent push messages](https://developers.line.biz/en/reference/messaging-api/#get-number-of-push-messages)
[Get number of sent multicast messages](https://developers.line.biz/en/reference/messaging-api/#get-number-of-multicast-messages)

**Comment by utatti** [comment]
#116 closes this.
