### ISSUE TITLE
How to receive location and image type response.

### ISSUE THREAD

**Issue by AliAyub007** [line/line-bot-sdk-nodejs#12]
when I tried receiving location via response it didn't send location I did it in this way. 

const answer = {
    type: "location",
    title: string,
    address: string,
    latitude: number,
    longitude: number,
}

 return client.replyMessage(event.replyToken, answer);

Kindly guide.

**Comment by noraesae** [comment]
Please check the following.

1. Are webhook events actually handled? You can check it by logging `event.replyToken` and see if it seems valid.
2. Are latitude and longitude valid? In the official doc, there is [an example object](https://devdocs.line.me/en/#location) you can test with.
3. Check if client secret and token are valid.

If checklist above doesn't help, could you please provide actual code? The snippet doesn't really help much to reason about the problem.

Thanks

**Comment by AliAyub007** [comment]
Yes this helped Thank you for the help.
