### ISSUE TITLE
Refactor to use async/await

### ISSUE THREAD

**Issue by justinzelinsky** [line/line-bot-sdk-nodejs#126]
Is there any desire to refactor the codebase to use `async`/`await`? I understand that the required version of Node is at least 6 but `async`/`await` has been around since Node 7.6. Is there a reason not to upgrade the minimum required version and use it?

Great codebase regardless, by the way.

**Comment by utatti** [comment]
As you've already mentioned, the only blocker for this is Node 6, [the LTS schedule of which ends in this April](https://github.com/nodejs/Release).

Surely, we're building TS to JS anyway, so we could let the TS compiler compile async/await into Promise + generator-based fallback. However, our decision is to wait until async/await is supported natively in ongoing LTS versions.

So all in all, I'm definitely thinking of moving to async/await after stopping the support for Node 6, so it happens in a while.
