### ISSUE TITLE
@types move to devDependencies

### ISSUE THREAD

**Issue by justinzelinsky** [line/line-bot-sdk-nodejs#127]
I love that this project includes TypeScript support. I was wondering if we could move `@types/body-parser`, `@types/file-type`, and `@types/node` to `devDependencies`. It doesn't look like the types you created in `types.ts` rely on any of these, unless I'm misunderstanding something.

Thoughts?

**Comment by utatti** [comment]
Please check out this: https://github.com/Microsoft/types-publisher/issues/81

In short, the types used in the published code should be in dependencies, so that they can be installed along with this SDK.

**Comment by utatti** [comment]
I close this issue, but feel free to ask me if something's unclear.

**Comment by justinzelinsky** [comment]
You know what? I reviewed the API this morning and I saw how you exposed access to these types. My bad :) Thanks again.
