### ISSUE TITLE
Returning two answers for one message event

### ISSUE THREAD

**Issue by AliAyub007** [line/line-bot-sdk-nodejs#13]
Can we return two answer for one message event? 
like in echo bot example it is like 

const echo = { type: 'text', text: event.message.text };
return client.replyMessage(event.replyToken, echo);

But can we return two answers and is there any way for this? 

const echo = { type: 'text', text: event.message.text };
const echo1 = { type: 'text', text: event.message.text };

return (client.replyMessage(event.replyToken, echo, client.replyMessage(event.replyToken, echo1));

**Comment by noraesae** [comment]
It is not possible to use a reply token more than once. If extra messages should be sent, push API should be used.

For the detail of reply token, please refer to the API documentation.

https://devdocs.line.me/en/#reply-message
