### ISSUE TITLE
How to use uri action

### ISSUE THREAD

**Issue by EriecTan** [line/line-bot-sdk-nodejs#133]
this.client.replyMessage(this.event.replyToken,{
      type : "uri",
      uri : "line://home/public/profile?id=xxxx",
 });

i try it but not working? i think my method is false

**Comment by utatti** [comment]
There is no separate URI message. You can just send URI as a text message.

```typescript
this.client.replyMessage(this.event.replyToken, {
  type: "text",
  text: "..."
});
```

For the types of messages, please refer to the documentation.

https://developers.line.biz/en/reference/messaging-api/#message-objects

**Comment by EriecTan** [comment]
so just paste the URI inside ( text : " " ) ? 
like this ?

this.client.replyMessage(this.event.replyToken, {
  type: "text",
  text: "line://home/public/profile?id=xxxx"
});

**Comment by utatti** [comment]
Yes. It must work. Or you can use Flex Message if you like to implement fancier UI.

**Comment by EriecTan** [comment]
thanks for fast respond!
