### ISSUE TITLE
If reply is more than 2000 characters, how can i Sending multiple messages?

### ISSUE THREAD

**Issue by zeteticl** [line/line-bot-sdk-nodejs#136]
line-bot-sdk-nodejs dont have wiki.....

**Comment by utatti** [comment]
As described in the API reference, the limit is 2000 characters and a reply token can be used only once.

- https://developers.line.biz/en/reference/messaging-api/#text-message
- https://developers.line.biz/en/reference/messaging-api/#send-reply-message

You should separate the message into multiple messages and send one with a reply token and the others as usual push messages.
