### ISSUE TITLE
How to get X-Line-Request-Id from client

### ISSUE THREAD

**Issue by songpr** [line/line-bot-sdk-nodejs#137]
How to get X-Line-Request-Id from client? Currently it return res.data so we cannot get the id from header.

Also X-Line-Request-Id is any useful when report issue to Line?

**Comment by xingoxu** [comment]
Hello there!
I've made a pr #151 .
If you are interested in and agree with that style, please give a thumb at that pull request.
Thank you!

**Comment by xingoxu** [comment]
Now you can get `X-LINE-Request-Id` from `responseData['x-line-request-id']` .
Released in v6.8.1.
