### ISSUE TITLE
'rm' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by justinlplummer** [line/line-bot-sdk-nodejs#14]
I am following the guide on this website. https://line.github.io/line-bot-sdk-nodejs/pages/getting-started/install.html
When I get to this step:

c:\line-bot-sdk-nodejs>npm run build

This is what follows:

> @line/bot-sdk@2.0.0 prebuild c:\line-bot-sdk-nodejs
> npm run lint && npm run clean

> @line/bot-sdk@2.0.0 lint c:\line-bot-sdk-nodejs
> tslint '{lib,test}/**/*.ts'

> @line/bot-sdk@2.0.0 clean c:\line-bot-sdk-nodejs
> rm -rf dist

'rm' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @line/bot-sdk@2.0.0 clean: `rm -rf dist`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @line/bot-sdk@2.0.0 clean script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\justin\AppData\Roaming\npm-cache\_logs\2017-07-12T10_15_07_639Z-debug.log

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @line/bot-sdk@2.0.0 prebuild: `npm run lint && npm run clean`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @line/bot-sdk@2.0.0 prebuild script 'npm run lint && npm run clean'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @line/bot-sdk package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run lint && npm run clean
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @line/bot-sdk
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @line/bot-sdk
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\line-bot-sdk-nodejs\npm-debug.log 

I see no file in c:\line-bot-sdk-nodejs...named  npm-debug.log 

Im running on windows 10 with 64 bit 

Please be kind enough to help with this issue  as I am just beginning to learn how to use node.js and i have performed hours of searches with answers telling me to change paths and change parts of the scripts and and other various solutions that i am not sure will even solve the issue. I don't want to end up digging myself into a deeper hole by messing with things like env variables if that is not the problem. Thank you very much for your time and consideration.

**Comment by justinlplummer** [comment]
also i left out that i am running on the latest version of npm and node 
 
debugging log found in the folder
 C:\Users\justin\AppData\Roaming\npm-cache_logs\2017-07-12T10_15_07_639Z-debug.log
as follows

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'c:\\line-bot-sdk-nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'clean' ]
2 info using npm@5.1.0
3 info using node@v6.11.0
4 verbose run-script [ 'preclean', 'clean', 'postclean' ]
5 info lifecycle @line/bot-sdk@2.0.0~preclean: @line/bot-sdk@2.0.0
6 info lifecycle @line/bot-sdk@2.0.0~clean: @line/bot-sdk@2.0.0
7 verbose lifecycle @line/bot-sdk@2.0.0~clean: unsafe-perm in lifecycle true
8 verbose lifecycle @line/bot-sdk@2.0.0~clean: PATH: c:\line-bot-sdk-nodejs\node_modules\npm\bin\node-gyp-bin;c:\line-bot-sdk-nodejs\node_modules\.bin;C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;c:\line-bot-sdk-nodejs\node_modules\.bin;C:\Program Files\Python36\Scripts\;C:\Program Files\Python36\;C:\Python27\;C:\Python27\Scripts;C:\Program Files\Java\jdk1.8.0_73\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;c:\python27;C:\Python27\Scripts;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Users\justin\AppData\Local\Microsoft\WindowsApps;C:\Users\justin\AppData\Roaming\npm
9 verbose lifecycle @line/bot-sdk@2.0.0~clean: CWD: c:\line-bot-sdk-nodejs
10 silly lifecycle @line/bot-sdk@2.0.0~clean: Args: [ '/d /s /c', 'rm -rf dist' ]
11 silly lifecycle @line/bot-sdk@2.0.0~clean: Returned: code: 1  signal: null
12 info lifecycle @line/bot-sdk@2.0.0~clean: Failed to exec clean script
13 verbose stack Error: @line/bot-sdk@2.0.0 clean: `rm -rf dist`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (c:\line-bot-sdk-nodejs\node_modules\npm\lib\utils\lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at EventEmitter.emit (events.js:191:7)
13 verbose stack     at ChildProcess.<anonymous> (c:\line-bot-sdk-nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:891:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
14 verbose pkgid @line/bot-sdk@2.0.0
15 verbose cwd c:\line-bot-sdk-nodejs
16 verbose Windows_NT 10.0.14393
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "c:\\line-bot-sdk-nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "clean"
18 verbose node v6.11.0
19 verbose npm  v5.1.0
20 error code ELIFECYCLE
21 error errno 1
22 error @line/bot-sdk@2.0.0 clean: `rm -rf dist`
22 error Exit status 1
23 error Failed at the @line/bot-sdk@2.0.0 clean script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by noraesae** [comment]
Hi there,

First of all, the problem occurred because `rm` is a command for *nix system. When `npm run build` is executed, `npm run clean` will run and it uses `rm` to remove the output directory. I have just uploaded a patch not to use `rm` in the `clean` task, and the problem must have gone in the latest `master` branch. Please pull it and try again.

Also, in the case you are not familiar with Node.js, you may not need to build it from the source. You can use the Node.js' package manager, [`npm`](https://www.npmjs.com/), to install Node.js packages.

```
npm install @line/bot-sdk
```

I strongly recommend installing it with npm, because, then, it can be managed in semver and you can safely rely on the version scheme. You can find documentations in the following links:

- https://docs.npmjs.com/

Thanks.
