### ISSUE TITLE
Support stay event added to beacon event

### ISSUE THREAD

**Issue by tkgauri** [line/line-bot-sdk-nodejs#186]
> In the Messaging API beacon event, a stay event has been added to indicate that the user is staying in the covered area of the beacon.

Messaging api reference: https://developers.line.biz/en/reference/messaging-api/#beacon-event
News: https://developers.line.biz/en/news/#a-stay-event-was-added-to-beacon-event-2019-12-06

**Comment by xingoxu** [comment]
Also duplicated with https://github.com/line/line-bot-sdk-nodejs/issues/181. I've added that to `To do` card.
