### ISSUE TITLE
Webhook working but on verifying with line it sends **A http status of the response was '404 Not Found'.**

### ISSUE THREAD

**Issue by AliAyub007** [line/line-bot-sdk-nodejs#2]
https://susi-linebot.herokuapp.com/ 
Here is the webhook link. 

**Kindly see this i will be very thankful if I can understand this**

// create LINE SDK client
const client = new line.Client(config);

// create Express app
// about Express itself: https://expressjs.com/
const app = express();

app.get('/',function(req, res){
	res.writeHead(200);
	res.write('Hi User');
	res.end();	
});
// register a webhook handler with middleware
// about the middleware, please refer to doc
app.post('https://susi-linebot.herokuapp.com/callback', line.middleware(config), (req, res) => {
  Promise
    .all(req.body.events.map(handleEvent))
    .then((result) => res.json(result));
});

// event handler
function handleEvent(event) {
  if (event.type !== 'message' || event.message.type !== 'text') {
    // ignore non-text-message event
    return Promise.resolve(null);
  }

  // create a echoing text message
  const echo = { type: 'text', text: event.message.text };

  // use reply API
  return client.replyMessage(event.replyToken, echo);
}

// listen on port
const port = process.env.PORT || 3000;
app.listen(port, () => {
  console.log(`listening on ${port}`);
});

**Comment by noraesae** [comment]
404 means express fails to find a request handler. I think to problem occurs because of the following line.

``` js
app.post('https://susi-linebot.herokuapp.com/callback', ...
```

It should be without protocol and domain:

``` js
app.post('/callback', ...
```

For the express usage, please refer to its documentation.

- https://expressjs.com/
