### ISSUE TITLE
I suggest util library for build text message

### ISSUE THREAD

**Issue by ufoo68** [line/line-bot-sdk-nodejs#201]
# I suggest util library for build text message

On `replyMessage`, almost user create a type of `TextMessage` for sending a message.  I suggest simple library of `buildTextMessage` on bellow snippet, for improve developer experience on `./util`. 

## code

```typescript
export function buildTextMessage(text: string | string[]): TextMessage[] {
  return toArray(text).map(value => ({ type: "text", text: value }));
}
```

## usege

```typescript
client.replyMessage(replyToken, buildReplyText('text'))
```

**Comment by xingoxu** [comment]
My opinion is helper util shouldn't be provided by official sdk. cc: @ianwith

**Comment by ufoo68** [comment]
Thank you for responce. I understood concepts of official SDK.
