### ISSUE TITLE
Specify `end-of-line` on prettier

### ISSUE THREAD

**Issue by ufoo68** [line/line-bot-sdk-nodejs#203]
# Specify `end-of-line` on prettier

In pre-commit, the system run prettier for format entire code. However, it convert unmodified file due to end-of-line on use windows-os. I suggest specify `end-of-line`  to `lf` on prettier based on this problem for windows-user committer.

```
"prettier": "prettier --parser typescript --trailing-comma all \"{lib,test}/**/*.ts\" --end-of-line lf"
```

**Comment by ufoo68** [comment]
This PR means change in behavior of end of line code when we use prettier on Windows, without specifying --end-of-line.

**Comment by xingoxu** [comment]
From [prettier option](https://prettier.io/docs/en/options.html):

```
By default, Prettier preserves a flavor of line endings a given file has already used. It also converts mixed line endings within one file to what it finds at the end of the first line.
```
Is it a bug on prettier side or is it a version problem?

Would you please try to remove `node_modules` and reinstall dependencies from `npm i`?

**Comment by ufoo68** [comment]
Sorry, this is problem on my git config. This is not related `prettier`....
