### ISSUE TITLE
What do u think about returning the raw http response headers?

### ISSUE THREAD

**Issue by hxc20060903** [line/line-bot-sdk-nodejs#208]
Well, when a message is sent via SDK, I want to tell the exact timestamp when it is accepted in LINE platform.
For messages sent by users, we can tell the time via webhook payload already.
I just want the quite opposite.

Meanwhile, I found that such data is available already in response headers when called via CURL.

**Comment by xingoxu** [comment]
We officially don't support any other properties in http header than `X-Line-Request-Id`.
https://developers.line.biz/ja/reference/messaging-api/#response-headers
I think this can be done by pure JavaScript.

```
await client.pushMessage(...);
let processedTime = Date.now();
```

**Comment by hxc20060903** [comment]
When we are building an async system, we should not trust a local server's timestamp, which leads to weird bugs potentially.
Hence, I don't think the solution u provided could be acceptable

**Comment by xingoxu** [comment]
We don't support timestamp in http header officially at present.
Please handle it by yourself.
If you have any suggestion, please ask https://contact.line.me/serviceId/11556
