### ISSUE TITLE
[feature request] Support LINE Notify

### ISSUE THREAD

**Issue by taichunmin** [line/line-bot-sdk-nodejs#209]
Because LINE@ has been migrate to Official Account. Some developer choose to use LINE Notify. I think we can add support LINE Notify API. [API docs](https://notify-bot.line.me/doc/en/)

* [ ] Generate URL to LINE Notify authorize page: `GET https://notify-bot.line.me/oauth/authorize`
* [ ] `POST https://notify-bot.line.me/oauth/token`
* [ ] `POST https://notify-api.line.me/api/notify`
* [ ] `GET https://notify-api.line.me/api/status`
* [ ] `POST https://notify-api.line.me/api/revoke`
* [ ] LINE Notify settings when initializing sdk.
* [ ] Error handling
* [ ] docs

**Comment by tkgauri** [comment]
@taichunmin as this is sdk for LINE Messaging api, we won't implement LINE Notify apis here.
