### ISSUE TITLE
How can i get userId who not added the bot as a friend

### ISSUE THREAD

**Issue by chooco13** [line/line-bot-sdk-nodejs#24]
Hi :)
thank you for updating to 3.0.0

I have one question

in [line api docs](https://devdocs.line.me/en/#get-group-room-member-profile). they say
> This can be the user ID of a user who has not added the bot as a friend or has blocked the bot

but how can i know userId who not added the bot as a friend?
when I logged event, not added the bot as a friend users don't return userId. (only return groupId or roomId)

this function should be use with `Get group/room member IDs`?
if so, I think `Get group/room member profile` also should have Info like `Get group/room member IDs` in line api docs

Info mean this message
> This feature is only available for LINE@ Approved accounts or official accounts.

**Comment by noraesae** [comment]
Hello,

If a user has agreed to *Official Accounts Terms of Use*, userId will be returned from a usual events. For the detailed information, please refer to the following link:

- https://developers.line.me/messaging-api/obtaining-user-consent
