### ISSUE TITLE
How can i get  the number of how many group  does my bot join?

### ISSUE THREAD

**Issue by zeteticl** [line/line-bot-sdk-nodejs#245]
How can i get  the number of how many group  does my bot join?

**Comment by xingoxu** [comment]
I think no API can get that information directly.
But maybe you can try the combination of `join` event and `leave` event.
https://developers.line.biz/en/reference/messaging-api/#join-event

I haven't tried it yet so I can't ensure it.
By the way, you can ask questions about Message API at [LINE Developers Community](https://www.line-community.me/en/questions). There will be API Expert to answer your question.

**Comment by xingoxu** [comment]
I will close this issue since it's a question and it has been a while from the last response.
If you still have any questions related to this topic, please re-open this issue.
