### ISSUE TITLE
middleware skips signature validation when 'x-line-signature' header is not set.

### ISSUE THREAD

**Issue by musou1500** [line/line-bot-sdk-nodejs#25]
in [middleware.ts](https://github.com/line/line-bot-sdk-nodejs/blob/master/lib/middleware.ts#L24)
```typescript
    const signature = req.headers["x-line-signature"] as string;

    if (!signature) {
      next();
      return;
    }
```

what happens if someone request without `x-line-signature` header?

**Comment by noraesae** [comment]
In the case, the body will not be parsed. However, if any body parser is used after the middleware, the body will be parsed as usual and the server can be spoofed as you assumed. It may be better to throw `SignatureValidationFailed` for the case.

**Comment by musou1500** [comment]
@noraesae I think so too. I wrote it (#26).
