### ISSUE TITLE
[BUG] HTTPClient config not work

### ISSUE THREAD

**Issue by 5987dogking** [line/line-bot-sdk-nodejs#252]
## Bug Report

Hi,
```
const client = new line.Client({
        channelAccessToken: config.channelAccessToken,
        channelSecret: config.channelSecret,
        httpConfig: {
            headers: { 'XXXX': 'XX' }
        }
    });
```
httpConfig headers Not Work,
/node_modules/@line/bot-sdk/dist/http.js on line 32
```
    async post(url, body, config) {
        const res = await this.instance.post(url, body, Object.assign({ headers: Object.assign({ "Content-Type": "application/json" }, (config && config.headers)) }, config));
        return this.responseParse(res);
    }
```
It should be like this
```
async post(url, body, config = this.config)
```
And it work for me.
Have a nice day.

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Node.js Version v12.18.3
 - line-bot-sdk-nodejs version(s) 7.0.0

**Comment by xingoxu** [comment]
It's not a bug.
Actually it's a config only for the whole client `timeout` and just for extendable, I created `httpConfig`.

The client doesn't support customizing the HTTP header now.
If there are any needs, please open a new issue.

**Comment by 5987dogking** [comment]
@xingoxu Thx u,
But I need to add a header that I can ues some **NEW API**.  
Any way,I just do it on my project,and it work.  
I look forward to opening this feature in the future.  
Have a nice day.
