### ISSUE TITLE
follow unfollow events

### ISSUE THREAD

**Issue by pbsmediatech** [line/line-bot-sdk-nodejs#260]
I'm not able to get either follow and unfollow events.
I am wondering whether this is a code specific issue or because the messaging channel is not verified.

**Comment by xingoxu** [comment]
I think it should be not related to verified or not.
And SDK should have the ability to get the unfollow event as typescript only help us coding not inferring the content of the incoming event.

How about your code? May I see your code? So I can replay it at local and take action. You can paste only key part of your code.

**Comment by pbsmediatech** [comment]
At this stage, I'm just logging out what the request the webhook receives.
I don't think the webhook gets called for the events in question.
