### ISSUE TITLE
[BUG] axios vulnerability issue

### ISSUE THREAD

**Issue by ryanebro** [line/line-bot-sdk-nodejs#273]
## Bug Report

**Describe the bug**
axios dependency should be updated to  0.21.1 or later
https://www.npmjs.com/advisories/1594

**To Reproduce**
1. run npm audit

**Screenshots**
![image](https://user-images.githubusercontent.com/27665903/103992671-6b95ed80-51cf-11eb-9cb7-778c0316aa08.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Node.js Version: 12.18.4
 - line-bot-sdk-nodejs version(s): 7.2.0

**Comment by Mitko-Kerezov** [comment]
When will this be released?

**Comment by songpr** [comment]
This have been open for months for High vulnerability, why it haven't been released?

**Comment by xingoxu** [comment]
This should has been released in 7.3.0
