### ISSUE TITLE
Messaging API - January 2021 update

### ISSUE THREAD

**Issue by tkgauri** [line/line-bot-sdk-nodejs#274]
News: https://developers.line.biz/en/news/2021/01/20/messaging-api-update-january-2021/
- [ ] [Get narrowcast message status properties to know acceptedTime and completedTime](https://developers.line.biz/en/reference/messaging-api/#get-narrowcast-progress-status)
- [ ] [Text message type properties to support user-mention](https://developers.line.biz/en/reference/messaging-api/#wh-text)

**Comment by alamchrstn** [comment]
hi, when would user-mention update be live in `master`? And another question, would there be any plan to support mentioning user in reply message of a bot?

Thanks in advance!

**Comment by tkgauri** [comment]
@alamchrstn This would be implemented soon. 

>would there be any plan to support mentioning user in reply message of a bot?
Yes, there's plan to support bot to user mention in future. Once released, it will be announced on https://developers.line.biz/en/news/.
