### ISSUE TITLE
some image url is sent as an error.

### ISSUE THREAD

**Issue by Flaze07** [line/line-bot-sdk-nodejs#281]
## Bug Report
Hi, so when I tried to send an image from the url https://ik.imagekit.io/Flaze/WTFlaze.png, it is sent as an error, however, when I sent the image from this link https://res.cloudinary.com/djtlmqkoq/image/upload/v1617126723/WTFlaze_jqtrpb.png ( both are the same image on different cdn site ). It works. Imagekit properly supports TLS 1.2, and fully complies with what the messaging API requires.

**To Reproduce**
1. Use the 
```
await client.replyMessage(replyToken, {
        type: 'image',
        originalContentUrl: imageUrl,
        previewImageUrl: imageUrl,
    }).catch(error => console.log(error));
```
2. set imageUrl as https://ik.imagekit.io/Flaze/WTFlaze.png
3. Wait for the bot to send the image
4. Sees the image as an error

what's supposed to happen is that the image is sent, instead of an error

![failure](https://user-images.githubusercontent.com/12490480/113036854-f67af880-91be-11eb-872e-b1a3279e77b0.png)

 - OS: Windows
 - Node.js Version [e.g. Node 14]
 - line-bot-sdk-nodejs version(s) 7.2.0

**Comment by xingoxu** [comment]
https://developers.line.biz/en/reference/messaging-api/#image-message
According to the document, `Message Object` only supports JPEG or PNG.

`https://ik.imagekit.io/Flaze/WTFlaze.png` 
The `content-type` header in this url's response is `image/webp`.
![image](https://user-images.githubusercontent.com/8542907/113080199-7a5dd080-9211-11eb-8109-4860481e2f30.png)

**Comment by xingoxu** [comment]
You can use any HTTP utility to inspect the request and response.
The image I uploaded is the network panel of Google Chrome's developer tools.

**Comment by Flaze07** [comment]
![image](https://user-images.githubusercontent.com/12490480/113084278-dfacc400-9207-11eb-85a6-26c9e9e6723e.png)

is this a valid way of checking? since this one returned .png

**Comment by xingoxu** [comment]
Yes.
And by the way, actually, the message is sent successfully. It just not showed correctly so Message API  and SDK side seem no any problem.
