### ISSUE TITLE
How to know what source which Line user add Line bot?

### ISSUE THREAD

**Issue by nguyendung17** [line/line-bot-sdk-nodejs#287]
Do this before creating an issue
We are working with Message API feature. My user can use line app then add our line bot to friend list by scan QR code.
We're printed QR code and stick them on information table in a school, office, subway station.

Problem
When user add a line bot to friend list, we don't know they added line bot from which QR code.

Solution
Somehow can we add some parameters to the QR code?

**Comment by taichunmin** [comment]
There are two unofficial method to source thich LINE user add LINE bot.

1. Use url shortener service.
2. Use LIFF with additional argements.
