### ISSUE TITLE
When will the next npm version be released?

### ISSUE THREAD

**Issue by morugu** [line/line-bot-sdk-nodejs#318]
I'd like to use rich menu aliases(https://github.com/line/line-bot-sdk-nodejs/pull/310) and oauth features(https://github.com/line/line-bot-sdk-nodejs/pull/291) from the SDK.

I hope it will be released in the near future.

**Comment by xingoxu** [comment]
I'm sorry for the late release and just released 7.5.0 right now.

**Comment by morugu** [comment]
thank you!
