### ISSUE TITLE
API Region lock

### ISSUE THREAD

**Issue by wolffparkinson** [line/line-bot-sdk-nodejs#319]
I have been using `line-bot-sdk-nodejs` for quite some time now and have various apps in production. What bothers me the most is during my local app development, I am unable to make API calls and perform E2E testing. I am able to use a VPN to bypass the region lock, but my other apps and services which are high on bandwidth take a toll.

Region : India

Is there something that could be done from LINE side ?

Due to this region lock, i have also been receiving many complaints for users in nearby countries which are unable to access various services like LINE Login , LIFF and Notify.

Have contacted ISP as well, but of no use.

```shell
originalError: Error: connect ETIMEDOUT 13.127.247.216:443
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16) {
    errno: -4039,
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '13.127.247.216',
    port: 443,
    config: {
      url: 'https://api.line.me/v2/bot/profile/Ucc572c11cce2e35be1283afa2e4a0827',
      method: 'get',
      headers: [Object],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      adapter: [Function: httpAdapter],
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      validateStatus: [Function: validateStatus],
      transitional: [Object],
      data: undefined
    },
```

EDIT : Upon further inspection, servers are found to be at AWS, Mumbai and we are getting `ETIMEDOUT` connecting to the servers. Now i doubt it is ISP related block, more towards some issues with AWS, Mumbai servers proly.
Users connecting from Bangladesh are having same isssue, probably due to the fact that are also getting connected via AWS Mumbai server.

**Comment by xingoxu** [comment]
I'm sorry but I don't know what the server did in India.
I think there's an inquiry form that you can ask about the API problem.
https://developers.line.biz/en/faq/#how-do-i-report-an-issue
