### ISSUE TITLE
Rich Menu

### ISSUE THREAD

**Issue by agung-wete** [line/line-bot-sdk-nodejs#33]
Is there any plan to include [richmenu](https://developers.line.me/en/docs/messaging-api/reference/#rich-menu) ?

**Comment by utatti** [comment]
Hi, I cannot say when it’ll be shipped exactly, but I think implementation will be started in a while.

**Comment by musou1500** [comment]
@utatti @agung-wete Actually, I'm working on it. Can I make PR?

**Comment by utatti** [comment]
@musou1500 Yes, PR will be welcomed.

**Comment by musou1500** [comment]
@utatti thankyou. I'll make it soon.

**Comment by utatti** [comment]
Implemented in #34. There are still some issues though. I'll look into them in a while.

**Comment by agung-wete** [comment]
thank you @utatti @musou1500

**Comment by utatti** [comment]
Remaining issue has been resolved and the change has been released as v5.0.0. Thanks all.
