### ISSUE TITLE
1 moderate severity vulnerability found in the the sdk

### ISSUE THREAD

**Issue by songpr** [line/line-bot-sdk-nodejs#351]
## Bug Report

**Describe the bug**
1 moderate severity vulnerability

**To Reproduce**

1. npm audit

**Expected behavior**
no severity found

**Screenshots**

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Node 16
 - line-bot-sdk-nodejs 7.5.0

**Additional context**
                       === npm audit security report ===                        
                                                                                
┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ file-type vulnerable to Infinite Loop via malformed MKV file │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ file-type                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=16.5.4                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @line/bot-sdk                                                │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @line/bot-sdk > file-type                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://github.com/advisories/GHSA-mhxj-85r3-2x55            │
└───────────────┴──────────────────────────────────────────────────────────────┘
found 1 moderate severity vulnerability in 285 scanned packages
  1 vulnerability requires manual review. See the full report for details.

**Comment by ahitrov** [comment]
The vulnerability has been upgraded recently to High

┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ file-type vulnerable to Infinite Loop via malformed MKV file │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ file-type                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=16.5.4                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @line/bot-sdk                                                │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @line/bot-sdk > file-type                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://github.com/advisories/GHSA-mhxj-85r3-2x55            │
└───────────────┴──────────────────────────────────────────────────────────────┘

Can we get this PR merged and a new version of @line/bot-sdk published?
https://github.com/line/line-bot-sdk-nodejs/pull/349

**Comment by ahitrov** [comment]
@xingoxu can you prioritize this?

**Comment by tokuhirom** [comment]
Thanks for your reporting! We released v7.5.2, that includes #349.
