### ISSUE TITLE
[error] npm run build No matching files. Patterns tried: '{lib,test}/**/*.ts' !**/node_modules/** !./node_modules/**

### ISSUE THREAD

**Issue by ekapasha17** [line/line-bot-sdk-nodejs#37]
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\xampp\\htdocs\\line-bot-sdk-n
run" "prettier" "--" "-l"
npm ERR! node v9.0.0
npm ERR! npm  v3.7.5
npm ERR! code ELIFECYCLE
npm ERR! @line/bot-sdk@5.0.1 prettier: `prettier --parser typescript --trailing-comma
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @line/bot-sdk@5.0.1 prettier script 'prettier --parser typescri
 "-l"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @line/bot-sdk package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prettier --parser typescript --trailing-comma all '{lib,test}/**/*.ts' "-
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @line/bot-sdk
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @line/bot-sdk
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\xampp\htdocs\line-bot-sdk-nodejs\npm-debug.log

npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\xampp\\htdocs\\line-bot-sdk-n
run" "format:check"
npm ERR! node v9.0.0
npm ERR! npm  v3.7.5
npm ERR! code ELIFECYCLE
npm ERR! @line/bot-sdk@5.0.1 format:check: `npm run prettier -- -l`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @line/bot-sdk@5.0.1 format:check script 'npm run prettier -- -l
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @line/bot-sdk package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run prettier -- -l
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @line/bot-sdk
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @line/bot-sdk
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\xampp\htdocs\line-bot-sdk-nodejs\npm-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @line/bot-sdk@5.0.1 prebuild: `npm run format:check && npm run clean`
npm ERR! Exit status 1
npm ERR!
[npm-debug.log](https://github.com/line/line-bot-sdk-nodejs/files/1504098/npm-debug.log)

**Comment by utatti** [comment]
It seems glob matching is failing in Windows. Can you check if `lib/` and `test/` directories exist in the root and the following command succeeds?

```bash
prettier --parser typescript --trailing-comma all '{lib,test}/**/*.ts' -l
```

Can anybody confirm the issue occurring in other Windows machines?

**Comment by micksatana** [comment]
@utatti confirmed issue on windows. after `git clone` and `npm install` then `npm run test`, the error will occur. my environment run on windows 10, node 8.9.1 clean installation.

ps. on mac everything work fine.

**Comment by utatti** [comment]
Fixed in the latest master. Thanks @micksatana!

**Comment by NihalAhmedBismillah** [comment]
I am also running the same issue, but resolve by removing the quote, Thanks!
