### ISSUE TITLE
Message information for replied messages

### ISSUE THREAD

**Issue by wolffparkinson** [line/line-bot-sdk-nodejs#398]
How to receive message information for the messages which are reply to other messages
![1670103840227.jpg](https://user-images.githubusercontent.com/84867169/205463318-e44464b7-f8b8-45b8-83a7-47644d3712a8.jpg)

For example here, how do i get information about the original message which was replied to.

- [ x ] I have gone through the documentation
- [ x ] I have searched stackoverflow

Is this available via LINE Messaging API
And if not, any plans to implement this ?

**Comment by Yang-33** [comment]
Now you can use after https://github.com/line/line-bot-sdk-nodejs/issues/461 is resolved!
