### ISSUE TITLE
I use your examples/kitchensink deploy on heroku

### ISSUE THREAD

**Issue by bojunshi** [line/line-bot-sdk-nodejs#40]
I use your examples/kitchensink deploy on heroku but it just response 404

it's my herokuapp link
[https://exchange-v4.herokuapp.com/webhook](https://exchange-v4.herokuapp.com/webhook)
it's log
[https://imgur.com/a/2r5Lv](https://imgur.com/a/2r5Lv)
it's verify image
[https://imgur.com/GCB5piu](https://imgur.com/GCB5piu)

how can I fix it.

**Comment by utatti** [comment]
Will try making it work in Heroku.

**Comment by utatti** [comment]
Now I catch it. It's not `/webhook`, it's `/callback`. Please update the callback URL and try again.

I'll update README to include the information.

**Comment by bojunshi** [comment]
ok,I try ,thank you

**Comment by utatti** [comment]
Also, please don't forget to set env variables correctly.

<img width="786" alt="screen shot 2017-12-07 at 17 45 30" src="https://user-images.githubusercontent.com/1013641/33706159-81c7b4da-db76-11e7-864c-79304688ca7b.png">

**Comment by bojunshi** [comment]
[https://imgur.com/a/zzk27](https://imgur.com/a/zzk27)
it is right?

**Comment by utatti** [comment]
You don't need to set `PORT`, as it's automatically set by Heroku.

**Comment by utatti** [comment]
Please add the following `start` script into package.json, if not already.

``` json
"scripts": {
  "start": "node ." 
}
```

**Comment by bojunshi** [comment]
yes,I have
it is ok?
[https://imgur.com/a/bjaRA](https://imgur.com/a/bjaRA)

**Comment by utatti** [comment]
Correct. Have you restarted the app after setting the env variables? I've already confirmed that it works with the settings in my Heroku instance.

**Comment by bojunshi** [comment]
yes, I restart it ,and it is log.
[https://imgur.com/a/f25Pb](https://imgur.com/a/f25Pb)

**Comment by utatti** [comment]
It doesn't work with `GET`. Webhook message is sent via `POST`. Have you tested it with actual LINE client?

**Comment by bojunshi** [comment]
not yet ,because Verify not pass.
ok,I go to try,sent message

**Comment by bojunshi** [comment]
ohhhh,it work, it will echo message on my line.
but, it is ok ?
[https://imgur.com/a/zWI43](https://imgur.com/a/zWI43)

**Comment by utatti** [comment]
I think the message is because the server returns non-200 responses. It doesn't affect the hehaviour of webhook, so I would say it's okay. I guess the message will go in a while.

Anyway, good to hear it works 😄

**Comment by bojunshi** [comment]
thank you so much. :)
