### ISSUE TITLE
[BUG] defaultAction is not defined in TemplateButtons

### ISSUE THREAD

**Issue by inoue0124** [line/line-bot-sdk-nodejs#431]
## Bug Report

defaultAction is not defined in TemplateButtons

**Describe the bug**
The type error appears when I use TemplateButtons with defaultAction parameter.
It still works on runtime if I write @ts-ignore.

**To Reproduce**

1. use TemplateButtons with defaultAction parameter.
2. See typescript error

**Expected behavior**
defaultAction is included in the type of TemplateButtons

**Screenshots**
<img width="500" alt="Screenshot 2023-03-15 at 18 01 26" src="https://user-images.githubusercontent.com/27270240/225261242-631571ee-b7f2-4bed-869f-20c8d4780700.png">
<img width="500" alt="Screenshot 2023-03-15 at 18 01 36" src="https://user-images.githubusercontent.com/27270240/225261263-69558ea2-0b8c-46c9-9e0f-3e7dd432fc94.png">

**Environment (please complete the following information):**
 - OS: MacOS 13.2
 - Node.js Version v16.14.2
 - line-bot-sdk-nodejs version(s) 7.5.2

**Additional context**

**Comment by Yang-33** [comment]
This feature has been released as `8.0.0`.
