### ISSUE TITLE
Echobot test via GET method

### ISSUE THREAD

**Issue by lintangtimur** [line/line-bot-sdk-nodejs#44]
when I using php, i test push message via GET method `https://localhost:8000/callback and return success 
```php
$app->get('/callback', function (\Slim\Http\Request $req, \Slim\Http\Response $res, $args) {
            /**
             * @var \LINE\LINEBot
             */
            $bot = $this->get('bot');

            $textMessageBuilder = new \LINE\LINEBot\MessageBuilder\TextMessageBuilder('ping pong');

            $response = $bot->pushMessage(getenv('USERID'), $textMessageBuilder);
            if ($response->isSucceeded()) {
                echo 'Succeeded!';

                return;
            }
            // Failed
            echo $response->getHTTPStatus() . ' ' . $response->getRawBody();
```
now, i want to test using nodejs via GET, how to implement get method to push message. My code
```javascript
app.get('/callback', line.middleware(config), (req, res) => {
    
    Promise
    .all(req.body.events.map(handleEvent))
    .then((result) => res.json(result));  
});
```
result is
```
Error: no signature
    at T:\Tutorial\NodeJS\line_nodejs\node_modules\@line\bot-sdk\dist\middleware.js:16:18
```

**Comment by lintangtimur** [comment]
i fix this this problem like this
```javascript
app.get('/callback', (req, res) => {
  const config = {
    headers : {
      Authorization: "Bearer " +  process.env.CHANNEL_ACCESS_TOKEN,
      'Content-Type' : "application/json"
    }
  }

  const msg = {
    type : 'text', text: 'ping pong'
  };

  var to = process.env.USERID;
    axios.default
      .post('https://api.line.me/v2/bot/message/push', {
        messages: toArray(msg),
        to,
    }, config)
      .then((response) => console.log(response.data))
      .catch((err) => console.log(err));
    
});
```

**Comment by utatti** [comment]
How does your `config` look like? The middleware doesn't infer HTTP method, and the error message says config doesn't include `channelSecret` is not set. Anyway, good to hear that it's been fixed.

Please feel free to ask us if you have any further issues. Thanks!

**Comment by lintangtimur** [comment]
my config just contain channelToken and channelSecret. 
Line middleware is just for triggering incoming message from LINE server?
If i put `line.middleware` in `app.get` so it cant pushMessage?

actually the problem that i face is, when i create some new bot, i usually want to test it via browser(get request). 
**example**: im doing pushMessage in browser

**Comment by utatti** [comment]
Ah, now I get it. You can’t test it with GET requests, because the middleware refers to the request body and auth header. For the test usage, please look into [webhook-tester](https://github.com/line/line-bot-sdk-nodejs/tree/master/tools/webhook-tester) in this repository.

**Comment by lintangtimur** [comment]
Oh okay, thank you
