### ISSUE TITLE
[feature proposal] It’s better to have API impl for SDK to verify the preparation status of a video or audio for getting

### ISSUE THREAD

**Issue by nagauta** [line/line-bot-sdk-nodejs#443]
## at first
I check the issue i shared below is reproducable below.
Node.js: v16.18.1
LINE BOT SDK(Node.js) Version: 7.5.2

## Issue
getting contents that is "audio" or "video" will be failed when the content is not ready to be downloaded.
There is solution for above issue. I wait until the contents become ready to be downloaded, checking "video-or-audio-preparation-status" using api below. 
https://developers.line.biz/ja/reference/messaging-api/#verify-video-or-audio-preparation-status
But it seems that there is no SDK impl for above API. 

## proposal
It’s better to have API impl to for SDK verify the preparation status of a video or audio for getting.

`
GET https://api-data.line.me/v2/bot/message/{messageId}/content/transcoding
`

https://developers.line.biz/ja/reference/messaging-api/#verify-video-or-audio-preparation-status

I'd like to contribute for this feature if this proposal is reasonable.

**Comment by Yang-33** [comment]
duplicated (https://github.com/line/line-bot-sdk-nodejs/issues/443)
