### ISSUE TITLE
UnhandledPromiseRejectionWarning: Unhandled promise rejection 

### ISSUE THREAD

**Issue by ariaseta** [line/line-bot-sdk-nodejs#45]
Hi, I have tried using the echo-bot example, and then get error 

"UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): Error: Request failed with status code 400"

When click verify button. I have set up the channelAccessToken and channelSecret, do I miss something?

**Comment by lintangtimur** [comment]
buat bot apa mas?
