### ISSUE TITLE
Flex message update 4

### ISSUE THREAD

**Issue by YasSawada** [line/line-bot-sdk-nodejs#450]
News URL
https://developers.line.biz/en/news/2023/07/04/flex-message-update-4-released/

- [New bubble sizes added](https://developers.line.biz/en/news/2023/07/04/flex-message-update-4-released/#bubble-size-2023-07-04)
- [Font size and icon size can now be automatically scaled according to the font size setting](https://developers.line.biz/en/news/2023/07/04/flex-message-update-4-released/#size-scaling-2023-07-04)

**Comment by Yang-33** [comment]
This feature has been released as `8.0.0`.
