### ISSUE TITLE
Rich Menu Batch Control

### ISSUE THREAD

**Issue by YasSawada** [line/line-bot-sdk-nodejs#451]
News URL:
In the Messaging API, you can now replace or unlink the rich menu linked to the users in batches
https://developers.line.biz/en/news/2023/07/04/messaging-api-updated/

- [Replace or unlink the linked rich menus in batches](https://developers.line.biz/en/reference/messaging-api/#batch-control-rich-menus-of-users)
- [Get the status of rich menu batch control](https://developers.line.biz/en/reference/messaging-api/#get-batch-control-rich-menus-progress-status)
- [Validate a request of rich menu batch control](https://developers.line.biz/en/reference/messaging-api/#validate-batch-control-rich-menus-request)

**Comment by Yang-33** [comment]
This feature has been released as `8.0.0`.
