### ISSUE TITLE
Quote Message

### ISSUE THREAD

**Issue by YasSawada** [line/line-bot-sdk-nodejs#461]
News URL:
You can now send and receive quote messages using the Messaging API
https://developers.line.biz/en/news/2023/09/14/send-and-receive-quote-messages-using-the-messaging-api/

- [Send quote messages](https://developers.line.biz/en/docs/messaging-api/sending-messages/#send-quote-messages)
- [Receive quote messages sent by users via webhook](https://developers.line.biz/en/docs/messaging-api/receiving-messages/#receive-quote-messages-sent-by-user)
- [Get quote tokens via webhook](https://developers.line.biz/en/docs/messaging-api/get-quote-tokens/#get-quote-tokens-via-webhook)
- [Get quote tokens in the response when sending a message](https://developers.line.biz/en/docs/messaging-api/get-quote-tokens/#get-quote-tokens-in-the-response)
- [Example response when retrying a request that has been accepted once](https://developers.line.biz/en/docs/messaging-api/retrying-api-request/#example-response-for-retrying-request-already-accepted-once)

**Comment by puuga** [comment]
Waiting for this update on types.ts

**Comment by Yang-33** [comment]
@puuga  You can contribute sdk project by updating code!

**Comment by Yang-33** [comment]
https://github.com/line/line-bot-sdk-nodejs/pull/477 modified webhook, and API request body definition.

There remains a task to define the response types for both the `push` and `reply` APIs.

**Comment by Yang-33** [comment]
This feature has been released as `8.0.0`.
