### ISSUE TITLE
How can I create a RichMenu for LINE with nodejs?

### ISSUE THREAD

**Issue by kimjinyam** [line/line-bot-sdk-nodejs#49]
Hello, 
How can I create a RichMenu for LINE with nodejs?

I can't found the sample for nodejs code.
i found only php sample.

Can you please help me with this issue? 
Thank you.

**Comment by utatti** [comment]
There is a small sample code in the client API reference in the documentation.

- https://line.github.io/line-bot-sdk-nodejs/pages/api-reference/client.html#rich-menu

Also, the API is almost the 1-on-1 match of REST API. It may be worth checking the Messaging API documentation too.

- https://developers.line.me/en/docs/messaging-api/reference/#rich-menu
- https://developers.line.me/en/docs/messaging-api/using-rich-menus/

Please let me know if you have any further issue.
