### ISSUE TITLE
Bump up minor version automatically or semi-automatically

### ISSUE THREAD

**Issue by Yang-33** [line/line-bot-sdk-nodejs#494]
After https://github.com/line/line-openapi is updated, we need to update minor version and open pull request manually.
This can be automated(or semi-automated). Other sdk projects bump up its version by
- release event(https://github.com/line/line-bot-sdk-java/blob/b0a97f969e8af6c8b577c1201d0f69c593def548/.github/workflows/publish.yml#L26)
- github actions(using dispatch_workflow https://github.com/line/line-bot-sdk-python/blob/8db5c5b7735345b615c3002865fba0ecb511edaf/.github/workflows/bump-minor-version.yml#L28)
  - `npm version minor` works...? 

anything is acceptable!

**Comment by tokuhirom** [comment]
Java SDK's style is looks good to me
