### ISSUE TITLE
Bad request with examples

### ISSUE THREAD

**Issue by quentinbt** [line/line-bot-sdk-nodejs#51]
Hi,

When I try your basics examples I get a Bad Request every time I try to verify my webhook from the console.

I  just c/p your code and deploy it on heroku

**Comment by quentinbt** [comment]
Yes I did

**Comment by utatti** [comment]
Can I have a Heroku log?

**Comment by dplusic** [comment]
When you verify, the `replyToken` in `event` is not valid.
Therefore, you must not call the `replyMessage` in verifying.

**Comment by utatti** [comment]
Closed for inactivity.
