### ISSUE TITLE
Installing @line/bot-sdk via npm throws an error that says "new line.messagingApi is undefined".

### ISSUE THREAD

**Issue by johnkao3** [line/line-bot-sdk-nodejs#511]
## Bug Report

**Describe the bug**
new line.messagingApi.MessagingApiClient get error message "TypeError: Cannot read properties of undefined (reading 'MessagingApiClient')"

**To Reproduce**

1. npm install @line/bot-sdk
2. Example code is [Basic-usage](https://line.github.io/line-bot-sdk-nodejs/getting-started/basic-usage.html#synopsis)
3. Run 

**Expected behavior**
No Error Message or Like [Official Example](https://github.com/line/line-bot-sdk-nodejs/tree/master/examples/echo-bot)

**Environment (please complete the following information):**
 - OS: macOS 13.5.1
 - Node.js Version 18.7.0
 - line-bot-sdk-nodejs version(s) 7.7.0

**Comment by tokuhirom** [comment]
You may need to use following importing section.

https://github.com/line/line-bot-sdk-nodejs/blob/6c92e9623423a737e5ce473071078de125c89923/docs/getting-started/basic-usage.md?plain=1#L12C1-L15

**Comment by johnkao3** [comment]
> You may need to use following importing section.
> 
> https://github.com/line/line-bot-sdk-nodejs/blob/6c92e9623423a737e5ce473071078de125c89923/docs/getting-started/basic-usage.md?plain=1#L12C1-L15

Thanks for your help. But I still get same error message.

<img width="852" alt="截圖 2023-10-06 下午8 09 49" src="https://github.com/line/line-bot-sdk-nodejs/assets/21374882/63a26d0d-651b-4ac1-9c95-88e635311840">

This is my JS code and package.json

```
const line = require('@line/bot-sdk');
const express = require('express')
const app = express()
const port = 8100

// create LINE SDK config from env variables
const config = {
  channelAccessToken: process.env.CHANNEL_ACCESS_TOKEN,
  channelSecret: process.env.CHANNEL_SECRET,
};

// create LINE SDK client
const client = new line.messagingApi.MessagingApiClient({
  channelAccessToken: process.env.CHANNEL_ACCESS_TOKEN
});

app.get('/', line.middleware(config), (req, res) => {
  Promise
    .all(req.body.events.map(handleEvent))
    .then((result) => res.json(result))
    .catch((err) => {
      console.error(err);
      res.status(500).end();
    });
})

// event handler
function handleEvent(event) {
  if (event.type !== 'message' || event.message.type !== 'text') {
    // ignore non-text-message event
    return Promise.resolve(null);
  }

  // create an echoing text message
  const echo = { type: 'text', text: event.message.text };

  // use reply API
  return client.replyMessage({
    replyToken: event.replyToken,
    messages: [echo],
  });
}

app.listen(port, () => {
  console.log(`Example app listening on port ${port}`)
})
```

```
{
  "name": "line-message-api",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@line/bot-sdk": "^7.7.0",
    "express": "^4.18.2"
  }
}

```

And I find the difference between "npm install @line/bot-sdk" and "git clone https://github.com/line/line-bot-sdk-nodejs to build source"

<img width="1418" alt="截圖 2023-10-06 下午8 15 53" src="https://github.com/line/line-bot-sdk-nodejs/assets/21374882/b017d7ad-4518-4c22-b749-44e81f1c6a7b">

**Comment by cola119** [comment]
@johnkao3 I encountered a similar issue with the documentation discrepancies, just like you did. It appears that the current documentation hosted at [https://line.github.io/line-bot-sdk-nodejs](https://line.github.io/line-bot-sdk-nodejs/#getting-started) is generated from the latest commit in the master branch, which explains the differences from v7.7 that your code is referencing.
I expect this issue will be resolved in #512. You can also check the corresponding documentation by going git log back. For your reference, here is the documentation for v7.7 you should refer: https://github.com/line/line-bot-sdk-nodejs/blob/v7.7.0/docs/guide/client.md

**Comment by Yang-33** [comment]
@johnkao3 thank you for report, and we're sorry for confusing you.

The latest library (v8.0.0) has been released, so document and code are fully updated. Could you try to use the latest line-bot-sdk again?

**Comment by Yang-33** [comment]
Thank you!
