### ISSUE TITLE
Use fetch() function instead of axios

### ISSUE THREAD

**Issue by k-kozika** [line/line-bot-sdk-nodejs#531]
I wanted to use this with Cloudflare Workers. However, in Workers, only the fetch() function is supported, so axios cannot be used (there is a similar issue with axios)
## Why are you still using it?
I don't think axios is necessary anymore The [fetch() function is officially supported by Node.js](https://developer.mozilla.org/en-US/docs/Web/API/fetch#browser_compatibility), so I don't think there is any need to absorb differences in the environment anymore.
Additionally, the build size is reduced somewhat.

**Comment by tokuhirom** [comment]
patches welcome :)

**Comment by k-kozika** [comment]
Is it okay to close this?

**Comment by Yang-33** [comment]
From line-bot-sdk-nodejs v9.0.0, clients (except for deprecated client) won't use axios.

**Comment by k-kozika** [comment]
👏
