### ISSUE TITLE
TypeError: Data must be a string or a buffer 

### ISSUE THREAD

**Issue by thanonk** [line/line-bot-sdk-nodejs#54]
I am using line-bot-sdk on Google Firebase (cloud function).
The function was successfully deployed and received a webhook event but it throw error.
> TypeError: Data must be a string or a buffer.

It appears to be from the "Crypto" in validateSignature function, which is called from "middleware.ts".
I didn't do any manual signature validation while testing. 
Please help.

**Comment by utatti** [comment]
The middleware itself is to validate the signature. If you use the middleware, it validates the request automatically and it is the recommended way. However, Firebase parses request body in advance and the middleware fails to process the body.

Here is a duplicated issue: #6

I’m not sure Firebase now provides raw request body. If not, please implement your own validation checker or just drop the middleware.
