### ISSUE TITLE
Can I Invite another Bot in chat room or Create Chat room by using Message API?

### ISSUE THREAD

**Issue by kimjinyam** [line/line-bot-sdk-nodejs#55]
Hello, Can I Invite another Bot in chat room or Create Chat room by using Message API?

I want to know whether the following situation can be made to be available by using Messaging API. 
Situation : When the chatbot A is in the chat room with me. So there are two in chat room. 
Case 1. I want to invite another chatbot B in our chat room by using replyMessage. 
Case 2. I want to join another chat room with chatbot C. By using replyMessage, can I create another chat room with chatbot C and me together ?

**Comment by utatti** [comment]
`replyMessage` doesn't invite a bot or create a room. It only replies a message to the original room where the bot received the message. For the time being there is API neither to invite any member nor to create a room or a group.

FYI, you cannot have 2 bots in one group.

ref: https://developers.line.me/en/faq/messaging-api/
