### ISSUE TITLE
[BUG] Broken types for webhook.Event in v8

### ISSUE THREAD

**Issue by wolffparkinson** [line/line-bot-sdk-nodejs#555]
## Bug Report

**Describe the bug**
- Cannot infer types of webhook events in v8.

**To Reproduce**
1. Use `echo-bot-ts` example from this repository or clone this [standalone repro example](https://github.com/wolffparkinson/line-echo-bot-ts)
2. Install dependencies
3. Go to `index.ts`
4. In `function textEventHandler`, you will see type errors like :
  - `Property 'type' does not exist on type '{}'`
  - `Property 'text' does not exist on type '{}'.`
5. Same goes for all other events and their properties like `event.message.type`, `event.message.text`

**Expected behavior**
- It should infer the correct type of event when the relevant property is conditionally checked.
- Even event.type is not typesafe : resolves to `string | undefined` instead of `"message" | "postback" | "follow" ,,,`

```ts
function eventHandler(){
  if (event.type !== 'message')  return;
  
  // this should be of type : webhook.MessageEvent
  // instead it is webhook.MessageEvent | webhook.UnknownEvent
  event

  // This breaks the type inference on other properties of event
  // event.message -> unknown
}
```

**Screenshots**
![image](https://github.com/line/line-bot-sdk-nodejs/assets/84867169/32e895ef-1a99-4f11-ac06-bb8f510c4a93)

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04.3 LTS
 - Node.js Version : v20.9.0 (LTS)
 - line-bot-sdk-nodejs version(s) : 8.0.0

**Additional context**
```bash
# npm list
echo-bot-ts@0.0.0 /home/wolffparkinson/dev/line-bot-sdk-nodejs/echo-bot-ts
├── @line/bot-sdk@8.0.0
├── @types/express@4.17.20
├── @types/node@20.8.9
├── express@4.18.2
├── rimraf@5.0.5
└── typescript@5.2.2
```

**Cause**
- Probably cause is `UnknownEvent` and other unknown types generated by client generator to handle future events / properties

**Current workaround**
- using `WebhookEvent` (deprecated) in place of `webhook.Event`  for event handlers.

**Comment by Yang-33** [comment]
Thank you for report. I'll fix this.

**Comment by Yang-33** [comment]
@wolffparkinson https://github.com/line/line-bot-sdk-nodejs/releases/tag/v8.0.1 is released.

**Comment by Yang-33** [comment]
8.0.1 fixes this. https://github.com/line/line-bot-sdk-nodejs/releases/tag/v8.0.1
