### ISSUE TITLE
Is there any function in Messaging API that I can send a push message which is about chat message update?

### ISSUE THREAD

**Issue by kimjinyam** [line/line-bot-sdk-nodejs#56]
Hello, I have some questions about the function of Messaging API

After successful build by pushing new code to Heroku server, 
I want to send a sentence like "New Version Updated" to the Chat Bot in all chat rooms.

However, as I look at the Webhook Event list in the Messaging API, there is no event whether the chat bot is started or not.

I would be grateful if you could give me an advice or sample codes.

**Comment by utatti** [comment]
There is no 'start' of a chat bot, as LINE chatbot server is always working, and sending webhook requests regardless of existence of the webhook server itself.

There is only a 'start' of a webhook server, which is maintained by bot developers (you). If messages should be sent for restarting your webhook server, it should manually be handled. To send to all previous sources, source IDs should be cached somewhere outside the process' memory, e.g. databases like Redis.

Here is a quick sample (pseudo) code.

```js
var app // express app
var db // some database
var client // LINE SDK client

app.post('/webhook', middleware, (req, res) => {
  req.body.events.forEach(handleEvent);
  ...
});

async function handleEvent(event) {
  const sourceId = event.source.groupId || event.source.roomId || event.source.userId;
  await db.add(sourceId);
  ...
}

app.listen(PORT, async () => {
  const ids = await db.getList();
  ids.forEach(id => client.pushMessage(id, { type: 'text', text: 'updated!' });
});
```

There may not be an event to automatically capture the restart of webhook server, as LINE chatbot server does not (and cannot) know whether the actual webhook server has been restarted (or even online).
