### ISSUE TITLE
Is it possible to use the Messaging API in order to control the 1: 1 chat feature supported by LINE @ App?

### ISSUE THREAD

**Issue by kimjinyam** [line/line-bot-sdk-nodejs#57]
I would like to switch to LINE@App 1-on-1 chat mode, only when the customer requests (input keyword or enter Event in RichMenu or Button Template).
Because 1: 1 chat mode does not respond automatically. 
Can this be implemented with the Messaging API?

ps.
LINE @ Enable Messaging API Settings in App Manager

Enabling the API is a permanent action and you will not be able to use the features listed below.
• 1-on-1 Chat
• LINE @ App

If I use the Messaging API, will I be unable to work with LINE @ App?

**Comment by kimjinyam** [comment]
![screen shot 2018-02-20 at 4 02 27 pm](https://user-images.githubusercontent.com/22905074/36411159-841597a4-1657-11e8-8830-f0084a96e4ed.png)

Attach a picture to help you understand the question.

**Comment by utatti** [comment]
Thank you for the additional information.

It is currently not possible with Messaging API. I guess this question may be moved to line-platform-feedback. Here is the link.

- https://github.com/line/line-platform-feedback

Sorry for the inconvenience, but please leave an issue in the repository.

**Comment by kimjinyam** [comment]
OK Thank you.
답변 감사합니다. 새해복 많이 받으세요.
