### ISSUE TITLE
User language / localisation API?

### ISSUE THREAD

**Issue by gfmio** [line/line-bot-sdk-nodejs#58]
Hi,

Quick question: As LINE is used internationally, is there any way to get a user's preferred language / localisation from the API? Or do I need to have some kind of dialogue where my bot asks a user, which language he/she would like to interact with?

Thanks,
@gfmio

**Comment by utatti** [comment]
I'm afraid there's none yet. For the time being, it should manually be handled by bot developers. However, this kind of requests have been being issued for a while and I guess it's worth elaborating this.

For feature request, [line-platform-feedback](https://github.com/line/line-platform-feedback) is a better place. Can you upload an issue there?

**Comment by gfmio** [comment]
Will do, thanks!
