### ISSUE TITLE
Method unlinkRichMenuFromUser receive error "The request method, 'DELETE', is not supported"

### ISSUE THREAD

**Issue by vincen7su** [line/line-bot-sdk-nodejs#59]
Error Log:
(I remove token, user Id and richmenu Id)
> { Error: Request failed with status code 405
    at HTTPError (/var/task/node_modules/@line/bot-sdk/dist/exceptions.js:34:9)
    at wrapError (/var/task/node_modules/@line/bot-sdk/dist/http.js:10:15)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
  statusCode: 405,
  statusMessage: '',
  originalError:
   { Error: Request failed with status code 405
       at createError (/var/task/node_modules/axios/lib/core/createError.js:16:15)
       at settle (/var/task/node_modules/axios/lib/core/settle.js:18:12)
       at IncomingMessage.handleStreamEnd (/var/task/node_modules/axios/lib/adapters/http.js:191:11)
       at emitNone (events.js:91:20)
       at IncomingMessage.emit (events.js:185:7)
       at endReadableNT (_stream_readable.js:974:12)
       at _combinedTickCallback (internal/process/next_tick.js:80:11)
       at process._tickDomainCallback (internal/process/next_tick.js:128:9)
     config:
      { adapter: [Function: httpAdapter],
        transformRequest: [Object],
        transformResponse: [Object],
        timeout: 0,
        xsrfCookieName: 'XSRF-TOKEN',
        xsrfHeaderName: 'X-XSRF-TOKEN',
        maxContentLength: -1,
        validateStatus: [Function: validateStatus],
        headers: [Object],
        method: 'delete',
        url: 'https://api.line.me/v2/bot/user/xxxxxxxxxxxxxxxxxxxxxxxx/richmenu/richmenu-xxxxxxxxxxxxxxxxxxxxxxxx',
        data: undefined },
     request:
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 6,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: false,
        sendDate: false,
        _removedHeader: {},
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Object],
        connection: [Object],
        _header: 'DELETE /v2/bot/user/xxxxxxxxxxxxxxxxxxxxxxxx/richmenu/richmenu-xxxxxxxxxxxxxxxxxxxxxxxx HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nAuthorization: Bearer xxxxxxxxxxxxxxxxxxxxxxxx=\r\nUser-Agent: @line/bot-sdk/5.2.0\r\nHost: api.line.me\r\nConnection: close\r\n\r\n',
        _headers: [Object],
        _headerNames: [Object],
        _onPendingData: null,
        agent: [Object],
        socketPath: undefined,
        timeout: undefined,
        method: 'DELETE',
        path: '/v2/bot/user/xxxxxxxxxxxxxxxxxxxxxxxx/richmenu/richmenu-xxxxxxxxxxxxxxxxxxxxxxxx',
        _ended: true,
        _redirectable: [Object],
        parser: null,
        res: [Object] },
     response:
      { status: 405,
        statusText: '',
        headers: [Object],
        config: [Object],
        request: [Object],
        data: [Object] } } }

In response data:

> { message: 'The request method, \'DELETE\', is not supported' }

**Comment by utatti** [comment]
I'm sorry that the client API was mis-implemented. `richmenuId` is not needed for the API. Will fix this.

**Comment by utatti** [comment]
A patch has been submitted. A new version will be released shortly.
