### ISSUE TITLE
Handle body when it's already parsed

### ISSUE THREAD

**Issue by utatti** [line/line-bot-sdk-nodejs#6]
**Moved from #5**

The problem is that we really do not know how `req.body` has been parsed by just checking its type (e.g. [Firebase Cloud Functions](https://firebase.google.com/docs/functions/http-events)). It's straight forward when its type is string, but things go difficult when it's an `object`. Calling `.toString()` cannot be a silver bullet as we do not know how it's implemented. If it results in a different string from the original request body, the validation process will silently fail which I do not want to happen.

I will first make it work with a string and a buffer, and look into how an object can be handled. Any idea is welcomed.

**Comment by noraesae** [comment]
After internal review, it's not very safe to support this kind of option, as there cannot be a silver-bullet function to revert an object into the original body buffer.

Rather than this, the case should be handled by using the `validateSignature()` function directly.

**Comment by noraesae** [comment]
By the way, pre-parsed string and buffer cases are handled as I described above.

**Comment by julianshen** [comment]
Thanks for looking into this. Agree it's not necessary to solve. It's a bad design from Google, and they seems also recognize this: https://issuetracker.google.com/issues/36252545 .

**Comment by noraesae** [comment]
Thanks for your understanding. Yes, I've checked the issue too. Implementation would be much easier if we could retrieve a raw body.

**Comment by skylinezum** [comment]
I apologize for reopening such an old issue, but just want to point out that there is now a rawBody in the request object for google cloud functions. It should solve this problem if you check for a rawBody key.

https://issuetracker.google.com/issues/36252545

**Comment by utatti** [comment]
Great news! Let's do this.
