### ISSUE TITLE
The type of AudioMessage.duration is incorrect.

### ISSUE THREAD

**Issue by Naetmul** [line/line-bot-sdk-nodejs#60]
In [lib/types.ts](../blob/master/lib/types.ts) line num 152, `AudioMessage.duration` should have `number` type, according to [API Reference](https://developers.line.me/en/docs/messaging-api/reference/#audio-message), the corresponding [JAVA SDK](https://github.com/line/line-bot-sdk-java/blob/master/line-bot-model/src/main/java/com/linecorp/bot/model/message/AudioMessage.java), and the corresponding [Go-lang SDK](https://github.com/line/line-bot-sdk-go/blob/master/linebot/message.go) (line num 103).

However, it is `string` type now (not `number` type).

**Comment by utatti** [comment]
I've just merged the PR. I'll release v6.0.1 shortly. Thanks!
