### ISSUE TITLE
GetProfile from not friend

### ISSUE THREAD

**Issue by felangga** [line/line-bot-sdk-nodejs#62]
Hello,
How to using getProfile to identify not friend user by using their userId. Is it possible to do that ?

**Comment by utatti** [comment]
It is not possible to use getProfile for non-friend users. Instead, for users who are in a room/group and not friends of a bot yet, you can use getGroupMemberProfile or getRoomMemberProfile API. For the detail, please refer to the official documentation or Node.js SDK's client API documentation.
