### ISSUE TITLE
Sending GIF?

### ISSUE THREAD

**Issue by austinhuang0131** [line/line-bot-sdk-nodejs#64]
Currently, when sending GIFs in a image message, the image is shown stabilized (i.e. Doesn't move). I know this is probably not the right place to inquire about a Line API specification, but is there any possibility of this feature getting supported?

I use Microsoft BotBuilder + my custom converter.

**Comment by utatti** [comment]
GIF is not currently supported with messaging API.

The question/feedback related with messaging API itself may be uploaded on [line-platform-feedback](https://github.com/line/line-platform-feedback) repository. Actually, there is a duplicated issue although it's not answered yet. I'm sorry that the response is not immediate, but it should be answered ASAP.

- https://github.com/line/line-platform-feedback/issues/76
