### ISSUE TITLE
Echo bot  - Request failed with status code 400

### ISSUE THREAD

**Issue by pchg9514** [line/line-bot-sdk-nodejs#65]
Hi,
I deployed the example - Echo bot on AWS EC2, but I could not verify the Webhook URL. 
I cloned this repo, cd to the echo bot, installed deps, and did the three configuration, CHANNEL_SECRET, CHANNEL_ACCESS_TOKEN and PORT(8080). My Webhook URL is https. Is there anything that I need to configure in order to run the echo bot?

The error message is as below. 

{ Error: Request failed with status code 400
    at wrapError (/home/ubuntu/line-bot-sdk-nodejs/examples/echo-bot/node_modules/@line/bot-sdk/dist/http.js:10:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
  statusCode: 400,
  statusMessage: '',
  originalError: 
   { Error: Request failed with status code 400
    at createError (/home/ubuntu/line-bot-sdk-nodejs/examples/echo-bot/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/ubuntu/line-bot-sdk-nodejs/examples/echo-bot/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/home/ubuntu/line-bot-sdk-nodejs/examples/echo-bot/node_modules/axios/lib/adapters/http.js:191:11)
    at IncomingMessage.emit (events.js:165:20)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
     config: 
      { adapter: [Function: httpAdapter],
        transformRequest: [Object],
        transformResponse: [Object],
        timeout: 0,
        xsrfCookieName: 'XSRF-TOKEN',
        xsrfHeaderName: 'X-XSRF-TOKEN',
        maxContentLength: -1,
        validateStatus: [Function: validateStatus],
        headers: [Object],
        method: 'post',
        url: 'https://api.line.me/v2/bot/message/reply',
        data: '{"messages":[{"type":"text","text":"Hello, world"}],"replyToken":"00000000000000000000000000000000"}' },
     request: 
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 6,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: null,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [TLSSocket],
        connection: [TLSSocket],
        _header: 'POST /v2/bot/message/reply HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nContent-Type: application/json\r\nAuthorization: Bearer p9XQZY+h1w8Qg98tOnsRIw+nrEWw9bESZ6CV+z2+eJl6ivRzat+PP7ZgVGmRXjLoP5KjRCYxN0AySIVP5yvE8T5hknQTgyIroQ3b0MDxu/WryATVeduMJw/dtaAflzFvl7rbrQsvKeeA1MfX+ez0IAdB04t89/1O/w1cDnyilFU=\r\nUser-Agent: @line/bot-sdk/5.2.0\r\nContent-Length: 100\r\nHost: api.line.me\r\nConnection: close\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Agent],
        socketPath: undefined,
        timeout: undefined,
        method: 'POST',
        path: '/v2/bot/message/reply',
        _ended: true,
        res: [IncomingMessage],
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        _redirectable: [Writable],
        [Symbol(outHeadersKey)]: [Object] },
     response: 
      { status: 400,
        statusText: '',
        headers: [Object],
        config: [Object],
        request: [ClientRequest],
        data: [Object] } } }

**Comment by utatti** [comment]
Hi,

In the log above, `replyToken` seems invalid (`00000000000000000000000000000000`). Was it a actual request from LINE?

**Comment by pchg9514** [comment]
Yes, I did it from Line Developer console.
![image](https://user-images.githubusercontent.com/37653474/37849672-d3ddc594-2e95-11e8-9ca8-331906f4ecc4.png)

**Comment by utatti** [comment]
It is not a real request. The verify test sends a dummy request with invalid replyToken, and it’s the reason why the reply API fails. Please try with actual requests sent from the LINE app.

**Comment by widapraponco** [comment]
> Yes, I did it from Line Developer console.
> ![image](https://user-images.githubusercontent.com/37653474/37849672-d3ddc594-2e95-11e8-9ca8-331906f4ecc4.png)

I got the same error when push verify button on the developer console, but when I tried to text from my LINE app, it works well
