### ISSUE TITLE
how to delete default menu show in the bot bottom

### ISSUE THREAD

**Issue by gwl002** [line/line-bot-sdk-nodejs#66]
DO anyone know how to delete the default menu show at the bottom of the bot.When I add a new rich menu in the Line@MANAGER,It show two menu,the default one and the new one I made.

**Comment by utatti** [comment]
It's a Node.js SDK repository, and I'm afraid it's not a place for general questions concerning messaging platform. They should be uploaded on [Q&A](https://www.line-community.me/questions). I'm really sorry, but please consider asking there again.

**Comment by gwl002** [comment]
The Line Developer Community is the most simple one I have ever seen.The Q&A Page have just 3 question and almost no answers.I don't know where to find support.So I tried to ask here.

**Comment by utatti** [comment]
Sorry for the inconvenience. The community page is new, maybe some-days new, so answers are still ongoing I guess. Now it has dozens answered. Alternatively, there is an inquiry form for LINE@ too.

- https://contact.line.me/serviceId/10829

I’m sorry again I cannot help with this kind of platform issues.
