### ISSUE TITLE
How FileEventMessage works

### ISSUE THREAD

**Issue by ridho9** [line/line-bot-sdk-nodejs#70]
I want to handle for FileEventMessage, but apparently FileEventMessage is not in union of EventMessage? Is this a bug or there's someway to do this?

**Comment by ridho9** [comment]
At [this](https://github.com/line/line-bot-sdk-nodejs/blob/master/lib/types.ts#L72-L78) part. I've tested by adding FileEventMessage and it works, but I don't know how to do a pr for this.

**Comment by utatti** [comment]
I’ll release a new version for this fix tomorrow.

**Comment by utatti** [comment]
Released via v6.0.2.
