### ISSUE TITLE
Added "ClipboardAction" type to types of actions

### ISSUE THREAD

**Issue by Arahabica** [line/line-bot-sdk-nodejs#703]
News:
https://developers.line.biz/en/news/2024/02/05/messaging-api-updated/

**Comment by Yang-33** [comment]
@Arahabica 
do you use lib/client.ts? It's deprecated. https://github.com/line/line-bot-sdk-nodejs/blob/85d8ac8d49a610bd25bd8e79916d84258af0b17c/lib/client.ts#L19

And clipboard actions is defined in https://github.com/line/line-bot-sdk-nodejs/pull/695/files.

**Comment by Arahabica** [comment]
@Yang-33 
Oh, I wasn't aware that lib/client.ts has been deprecated. Thank you for bringing this to my attention.
I resolve the issue by using the messaging-api module. Sorry for any inconvenience caused.
