### ISSUE TITLE
How to display sticker for message type sticker

### ISSUE THREAD

**Issue by mahadoang** [line/line-bot-sdk-nodejs#8]
Method display sticker for message type sticker

**Comment by noraesae** [comment]
What do you mean with 'display'? Can you please specify the case a little more?

**Comment by mahadoang** [comment]
i'm sorry.
english a little.
i want get sticker url or sticker content from receive message.

`"message": {
    "id": "325708",
    "type": "sticker",
    "packageId": "1",
    "stickerId": "1"
  }`

thank you.

**Comment by noraesae** [comment]
I am afraid it is not possible due to sticker copyright. A sticker's information and images belong to its creator or legal owner.

**Comment by mahadoang** [comment]
thank a lot.
and then i want to get file name and file type of message type  "image","video","file","audio" from content data

**Comment by noraesae** [comment]
For file message, there is `fileName` in webhook JSON. For other media types, for the time being, there is no way to retrieve the original file name and type. For content type returned by API, you can guess they are JPEG, MP4 and M4A, but they are not yet specified in spec, so may change.

**Comment by mahadoang** [comment]
Thank a lot.

**Comment by noraesae** [comment]
No worries :)

**Comment by neo125874** [comment]
@utatti hi, is there any way to get audio info(like sampleRate, encoding etc.) ?
Because of the use of sending the audio file to dialogflow for speech recognition.

Thanks!
