### ISSUE TITLE
[BUG] setup webhook following code in example doesn't work anymore

### ISSUE THREAD

**Issue by ddhp** [line/line-bot-sdk-nodejs#851]
## Bug Report

**Describe the bug**
as title, req.body will be undefined since there is no body parser

**To Reproduce**

following [this example](https://line.github.io/line-bot-sdk-nodejs/getting-started/basic-usage.html#synopsis) since body parser is removed from middleware https://github.com/line/line-bot-sdk-nodejs/pull/752

**Expected behavior**
we should add `app.use(express.json())` in the examples, so it would work expectedly

**Screenshots**
not applicable.

**Environment (please complete the following information):**
 - OS: Linux Alpine
 - Node.js Version 20.11.1
 - line-bot-sdk-nodejs version(s): 9.2.0

**Additional context**

**Comment by Yang-33** [comment]
Hi, thank you for using line-bot-sdk-nodejs, @ddhp!

As I ran the example in my local, I couldn't reproduce this. code without `app.use(express.json())` worked.

**Comment by Yang-33** [comment]
express: `4.19.2`

**Comment by ddhp** [comment]
Oh it might be because we are using app.use instead of app.post. If it’s working that’s fine. Sorry I didn’t totally follow the example before submitting the issue. I would close it now. Thank you
