### ISSUE TITLE
Proxy Support for sendReply and pushMessage

### ISSUE THREAD

**Issue by paulsherwinang** [line/line-bot-sdk-nodejs#9]
Hi,

The app I am running needs to proxy calls to the LINE API. Any tips or support for this in the SDK?

Thanks!

**Comment by noraesae** [comment]
Hello, sorry for the late reply.

As far as I understand, your app is in the environment where LINE API endpoints cannot be directly accessed? In the case, you may want to build a proxy server in the middle to receive a request from your app and forward it to the LINE API server. You can set the client to send requests to your proxy server domain:

https://github.com/line/line-bot-sdk-nodejs/blob/master/lib/urls.ts#L1

Please set `API_BASE_URL` to point your proxy.

If my understanding was wrong, could you please specify the case?

Thanks

**Comment by noraesae** [comment]
Closed for inactivity.
