### ISSUE TITLE
[BUG] issueChannelToken incorrect response

### ISSUE THREAD

**Issue by megenius** [line/line-bot-sdk-nodejs#938]
example bug response
{
  access_token: "",
  expires_in: 123456,
  ....
}

should be:
{
  accessToken: "",
  expiresIn: 123456,
  ....
}

**Comment by Yang-33** [comment]
https://developers.line.biz/en/reference/messaging-api/#issue-shortlived-channel-access-token

**Comment by Yang-33** [comment]
Hi, thank you for your using this SDK, @megenius!
https://www.npmjs.com/package/@line/bot-sdk/v/9.3.1 fixed this, thanks to @mokuzon .

**Comment by mokuzon** [comment]
@megenius Thank you reporting this!
This issue is fixed in https://github.com/line/line-bot-sdk-nodejs/releases/tag/v9.3.1
